heat_template_version: 2017-02-24

resources:
  freebsd_port:
    type: OS::Neutron::Port
    properties:
      network: "openshift-pod"
      name: "freebsd"
      fixed_ips: [{"subnet_id": "openshift-pod"}]

  freebsd:
    type: OS::Nova::Server
    properties:
      name: freebsd
      key_name: jenkins-openstack
      image: freebsd11
      flavor: m1.medium
      networks:
        - port: { get_resource: freebsd_port }
  
