heat_template_version: 2017-02-24

resources:
  windows_port:
    type: OS::Neutron::Port
    properties:
      network: "openshift-pod"
      name: "windows"
      fixed_ips: [{"subnet_id": "openshift-pod"}]

  windows:
    type: OS::Nova::Server
    properties:
      name: windows
      key_name: default
      image: w7
      flavor: m1.medium
      networks:
        - port: { get_resource: windows_port }
  
