apiVersion: "v1"
kind: "Pod"
metadata:
  name: "nginx"
  labels:
    name: "nginx"
    conf: "${APP_NAME}-${APP_VERSION}"
spec:
  containers:
    -
      name: "nginx"
      image: "nginx:latest"

      securityContext:
        privileged: true